In [57]:
import pandas as pd
df = pd.read_csv('cancer.csv', header = None, names = ['1','2','3', '4','5','6','7','8','9','10'])
df

1          2        3      4      5    6        7           8      9  \
0  '40-49'  'premeno'  '15-19'  '0-2'  'yes'  '3'  'right'   'left_up'   'no'   
1  '50-59'     'ge40'  '15-19'  '0-2'   'no'  '1'  'right'   'central'   'no'   
2  '50-59'     'ge40'  '35-39'  '0-2'   'no'  '2'   'left'  'left_low'   'no'   
3  '40-49'  'premeno'  '35-39'  '0-2'  'yes'  '3'  'right'  'left_low'  'yes'   
4  '40-49'  'premeno'  '30-34'  '3-5'  'yes'  '2'   'left'  'right_up'   'no'   

                       10  
0     'recurrence-events'  
1  'no-recurrence-events'  
2     'recurrence-events'  
3  'no-recurrence-events'  
4     'recurrence-events'

In [58]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np

label_encoder = LabelEncoder()
onehot_encoder= OneHotEncoder(sparse = False)
y = df['10']
X = df.drop(['10'], axis = 1)
X.shape[1]
encoded_x = None
feature = label_encoder.fit_transform(X['8'])
feature = feature.reshape(X['8'].shape[0], 1)
print(feature)
feature = onehot_encoder.fit_transform(feature)
feature
# if encoded_x is None:
#     encoded_x = feature
# else:
#     encoded_x = np.concatenate((encoded_x, feature), axis = 1)
# encoded_x

[[2]
 [0]
 [1]
 [1]
 [3]]


array([[ 0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [59]:
import numpy
from pandas import read_csv
# from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
# load data
# data = read_csv('datasets-uci-breast-cancer.csv', header=None)
data = df
dataset = data.values
# split data into X and y
X = dataset[:,0:9]
X = X.astype(str)
Y = dataset[:,9]
# encode string input values as integers
encoded_x = None
for i in range(0, X.shape[1]):
	label_encoder = LabelEncoder()
	feature = label_encoder.fit_transform(X[:,i])
	feature = feature.reshape(X.shape[0], 1)
	onehot_encoder = OneHotEncoder(sparse=False)
	feature = onehot_encoder.fit_transform(feature)
	if encoded_x is None:
		encoded_x = feature
	else:
		encoded_x = numpy.concatenate((encoded_x, feature), axis=1)
print("X shape: : ", encoded_x.shape)
encoded_x

X shape: :  (5, 22)


array([[ 1.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,
         1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,
         0.,  0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  0.,  1.,
         0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.],
       [ 1.,  0.,  0.,  1.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  0.,  0.,
         1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,
         0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.]])

In [4]:
import pandas as pd
df = pd.read_csv('Airbnb_data/listings_SanFan.csv')
# df['neighbourhood'].dropna(inplace=True)
# len(df['neighbourhood'].unique())
# a = sorted(list(df['neighbourhood'].unique()))
print(df.columns.values)


['id' 'listing_url' 'scrape_id' 'last_scraped' 'name' 'summary' 'space'
 'description' 'experiences_offered' 'neighborhood_overview' 'notes'
 'transit' 'access' 'interaction' 'house_rules' 'thumbnail_url'
 'medium_url' 'picture_url' 'xl_picture_url' 'host_id' 'host_url'
 'host_name' 'host_since' 'host_location' 'host_about' 'host_response_time'
 'host_response_rate' 'host_acceptance_rate' 'host_is_superhost'
 'host_thumbnail_url' 'host_picture_url' 'host_neighbourhood'
 'host_listings_count' 'host_total_listings_count' 'host_verifications'
 'host_has_profile_pic' 'host_identity_verified' 'street' 'neighbourhood'
 'neighbourhood_cleansed' 'neighbourhood_group_cleansed' 'city' 'state'
 'zipcode' 'market' 'smart_location' 'country_code' 'country' 'latitude'
 'longitude' 'is_location_exact' 'property_type' 'room_type' 'accommodates'
 'bathrooms' 'bedrooms' 'beds' 'bed_type' 'amenities' 'square_feet' 'price'
 'weekly_price' 'monthly_price' 'security_deposit' 'cleaning_fee'
 'guests_included

In [6]:
df['space'].unique()[:5]

array([ "This is more of an apartment or flat than a room. And while it may have all the charm of a Days Inn in Wisconsin – not that there's anything wrong with that – what you lose in style you gain in functionality. It's a great private place to sleep, hang out, do some work, watch some basic cable, and make a simple meal with the microwave/refrigerator/coffee maker kitchenette; full kitchen available also if you prefer. You have easy access to everything, and it's a darn good deal for the budget traveler.",
       nan,
       'This cute, spacious 2 flat in Lincoln Square is recently remodeled! The space is a Chicago-themed owner occupied 3-bedroom apartment located on the first floor. The kitchen was completely remodeled in the winter of 2016 with custom cabinets, granite countertops, and new appliances and is ready to host! It is fully equipped with a Kureig coffee maker, Vitamix blender, microwave, dishwasher, and all plates, cups, cooking utensils, and silverware are available fo

In [23]:
df['host_neighbourhood'].unique()

array(['Lincoln Square', nan, 'Uptown', 'Hyde Park', 'Kenwood',
       'Gay Village', 'Woodlawn', 'Rogers Park', 'West Ridge', 'Dunning',
       'Edgewater', 'Jefferson Park', 'Sauganash', 'North Park',
       'Albany Park', 'Avondale', 'Bucktown', 'Lakeview', 'Logan Square',
       'Kips Bay', 'Wicker Park', 'Chinatown', 'River North',
       'Humboldt Park', 'Lincoln Park', 'Old Town', 'Ukrainian Village',
       'West Town/Noble Square', 'River West', 'Boystown', 'Cambridge',
       'Wrigleyville', 'Miami Beach', 'Skid Row', 'Venice',
       'North Hollywood', 'Pilsen', 'West Loop/Greektown',
       'Near North Side', 'Garfield Park', 'South Beach',
       'Lower East Side', 'Bridgeport', 'Casco Antiguo', 'Loop',
       'East Harlem', 'Galewood', 'Austin', 'Little Italy/UIC',
       'Near West Side', 'South Loop/Printers Row', 'Andersonville',
       'Fenway/Kenmore', 'Barrio Logan', 'Bronzeville', 'Hollywood',
       'Norwood Park', 'Gold Coast', 'Streeterville', 'Valley Village',


In [24]:
df['room_type']

0          Private room
1          Private room
2          Private room
3          Private room
4          Private room
5          Private room
6          Private room
7          Private room
8       Entire home/apt
9       Entire home/apt
10      Entire home/apt
11      Entire home/apt
12      Entire home/apt
13      Entire home/apt
14      Entire home/apt
15      Entire home/apt
16      Entire home/apt
17      Entire home/apt
18      Entire home/apt
19      Entire home/apt
20      Entire home/apt
21      Entire home/apt
22      Entire home/apt
23      Entire home/apt
24      Entire home/apt
25      Entire home/apt
26         Private room
27         Private room
28      Entire home/apt
29      Entire home/apt
             ...       
5177        Shared room
5178       Private room
5179       Private room
5180        Shared room
5181       Private room
5182       Private room
5183       Private room
5184        Shared room
5185       Private room
5186       Private room
5187       Priva

In [36]:
from sklearn.cross_validation import ShuffleSplit
from sklearn.metrics import r2_score
from collections import defaultdict
from sklearn.datasets import load_boston
from sklearn.ensemble import RandomForestRegressor
import numpy as np
#Load boston housing dataset as an example
boston = load_boston()

X = boston["data"]
Y = boston["target"]
 
rf = RandomForestRegressor()
scores = defaultdict(list)
names = boston["feature_names"]
names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'],
      dtype='<U7')

In [37]:
Y

array([ 24. ,  21.6,  34.7,  33.4,  36.2,  28.7,  22.9,  27.1,  16.5,
        18.9,  15. ,  18.9,  21.7,  20.4,  18.2,  19.9,  23.1,  17.5,
        20.2,  18.2,  13.6,  19.6,  15.2,  14.5,  15.6,  13.9,  16.6,
        14.8,  18.4,  21. ,  12.7,  14.5,  13.2,  13.1,  13.5,  18.9,
        20. ,  21. ,  24.7,  30.8,  34.9,  26.6,  25.3,  24.7,  21.2,
        19.3,  20. ,  16.6,  14.4,  19.4,  19.7,  20.5,  25. ,  23.4,
        18.9,  35.4,  24.7,  31.6,  23.3,  19.6,  18.7,  16. ,  22.2,
        25. ,  33. ,  23.5,  19.4,  22. ,  17.4,  20.9,  24.2,  21.7,
        22.8,  23.4,  24.1,  21.4,  20. ,  20.8,  21.2,  20.3,  28. ,
        23.9,  24.8,  22.9,  23.9,  26.6,  22.5,  22.2,  23.6,  28.7,
        22.6,  22. ,  22.9,  25. ,  20.6,  28.4,  21.4,  38.7,  43.8,
        33.2,  27.5,  26.5,  18.6,  19.3,  20.1,  19.5,  19.5,  20.4,
        19.8,  19.4,  21.7,  22.8,  18.8,  18.7,  18.5,  18.3,  21.2,
        19.2,  20.4,  19.3,  22. ,  20.3,  20.5,  17.3,  18.8,  21.4,
        15.7,  16.2,